/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kawachi' at '7/4/15 2:43 PM' with Gradle 2.4
 *
 * @author kawachi, @date 7/4/15 2:43 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
